server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Authentication Service Routes
        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**

        # Customer Service Routes
        - id: customer-service
          uri: lb://customer-management-service
          predicates:
            - Path=/api/v1/customers/**

        # Car Management Service Routes
        - id: car-service
          uri: lb://car-management-service
          predicates:
            - Path=/api/v1/cars/**, /api/v1/manufacturers/**, /api/v1/suppliers/**

        # Renting Transaction Service Routes
        - id: renting-transaction-service
          uri: lb://renting-transaction-service
          predicates:
            - Path=/api/v1/rentals/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

application:
  jwt:
    secret-key: zYxfmMUEe8h1N9y6cYbAa6GvLjExF4z/YM+R9U56GNqslZfMGUINub49KZ1mD6CUKntDaKlZsKU9KZIgwl9qTw==
    expiration-ms: 86400000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
